Traceback (most recent call last):
  File "/home/ubuntu/varuna_examples/DeepLearningExamples/PyTorch/LanguageModeling/BERT/run_pretraining.py", line 840, in <module>
    args, final_loss, train_time_raw, global_step = main()
  File "/home/ubuntu/varuna_examples/DeepLearningExamples/PyTorch/LanguageModeling/BERT/run_pretraining.py", line 721, in main
    loss, overflow, grad_norm = model.step(batch)
  File "/home/ubuntu/varuna/varuna/varuna.py", line 280, in step
    self.average_loss, fwd_time = self.pipeline.run()
  File "/home/ubuntu/varuna/varuna/pipeline.py", line 296, in run
    self.worker(task[0], grad_mode, self.batches[task[1]])
IndexError: list index out of range
terminate called without an active exception
Traceback (most recent call last):
  File "/home/ubuntu/varuna_examples/DeepLearningExamples/PyTorch/LanguageModeling/BERT/run_pretraining.py", line 840, in <module>
    args, final_loss, train_time_raw, global_step = main()
  File "/home/ubuntu/varuna_examples/DeepLearningExamples/PyTorch/LanguageModeling/BERT/run_pretraining.py", line 721, in main
    loss, overflow, grad_norm = model.step(batch)
  File "/home/ubuntu/varuna/varuna/varuna.py", line 280, in step
    self.average_loss, fwd_time = self.pipeline.run()
  File "/home/ubuntu/varuna/varuna/pipeline.py", line 296, in run
    self.worker(task[0], grad_mode, self.batches[task[1]])
IndexError: list index out of range
terminate called without an active exception
Traceback (most recent call last):
  File "/home/ubuntu/varuna_examples/DeepLearningExamples/PyTorch/LanguageModeling/BERT/run_pretraining.py", line 840, in <module>
    args, final_loss, train_time_raw, global_step = main()
  File "/home/ubuntu/varuna_examples/DeepLearningExamples/PyTorch/LanguageModeling/BERT/run_pretraining.py", line 601, in main
    device, args = setup_training(args)
  File "/home/ubuntu/varuna_examples/DeepLearningExamples/PyTorch/LanguageModeling/BERT/run_pretraining.py", line 349, in setup_training
    torch.distributed.init_process_group(backend='gloo' if args.varuna else 'nccl', init_method='env://')
  File "/opt/conda/envs/varuna/lib/python3.9/site-packages/torch/distributed/distributed_c10d.py", line 602, in init_process_group
    default_pg = _new_process_group_helper(
  File "/opt/conda/envs/varuna/lib/python3.9/site-packages/torch/distributed/distributed_c10d.py", line 703, in _new_process_group_helper
    pg = ProcessGroupGloo(prefix_store, rank, world_size, timeout=timeout)
RuntimeError: Connection reset by peer
