Terminated
Traceback (most recent call last):
  File "/home/ubuntu/varuna_examples/Megatron-LM/pretrain_gpt2.py", line 170, in <module>
    pretrain(train_valid_test_datasets_provider, model_provider, forward_step,
  File "/home/ubuntu/varuna_examples/Megatron-LM/megatron/training.py", line 103, in pretrain
    model, optimizer, lr_scheduler = setup_model_and_optimizer(model_provider, get_batch_fn)
  File "/home/ubuntu/varuna_examples/Megatron-LM/megatron/training.py", line 280, in setup_model_and_optimizer
    args.iteration = load_checkpoint(model, optimizer, lr_scheduler)
  File "/home/ubuntu/varuna_examples/Megatron-LM/megatron/checkpointing.py", line 285, in load_checkpoint
    torch.distributed.barrier()
  File "/opt/conda/envs/varuna/lib/python3.9/site-packages/torch/distributed/distributed_c10d.py", line 2783, in barrier
    work.wait()
RuntimeError: [/opt/conda/conda-bld/pytorch_1646755888534/work/third_party/gloo/gloo/transport/tcp/pair.cc:598] Connection closed by peer [172.31.27.216]:62642
Traceback (most recent call last):
  File "/home/ubuntu/varuna_examples/Megatron-LM/pretrain_gpt2.py", line 170, in <module>
    pretrain(train_valid_test_datasets_provider, model_provider, forward_step,
  File "/home/ubuntu/varuna_examples/Megatron-LM/megatron/training.py", line 103, in pretrain
    model, optimizer, lr_scheduler = setup_model_and_optimizer(model_provider, get_batch_fn)
  File "/home/ubuntu/varuna_examples/Megatron-LM/megatron/training.py", line 280, in setup_model_and_optimizer
    args.iteration = load_checkpoint(model, optimizer, lr_scheduler)
  File "/home/ubuntu/varuna_examples/Megatron-LM/megatron/checkpointing.py", line 285, in load_checkpoint
    torch.distributed.barrier()
  File "/opt/conda/envs/varuna/lib/python3.9/site-packages/torch/distributed/distributed_c10d.py", line 2783, in barrier
    work.wait()
RuntimeError: [/opt/conda/conda-bld/pytorch_1646755888534/work/third_party/gloo/gloo/transport/tcp/pair.cc:598] Connection closed by peer [172.31.27.216]:30083
Traceback (most recent call last):
  File "/home/ubuntu/varuna_examples/Megatron-LM/pretrain_gpt2.py", line 170, in <module>
    pretrain(train_valid_test_datasets_provider, model_provider, forward_step,
  File "/home/ubuntu/varuna_examples/Megatron-LM/megatron/training.py", line 131, in pretrain
    iteration = train(forward_step_func if not args.varuna else varuna_step_func,
  File "/home/ubuntu/varuna_examples/Megatron-LM/megatron/training.py", line 503, in train
    loss_dict, skipped_iter = train_step(forward_or_varuna_step_func,
  File "/home/ubuntu/varuna_examples/Megatron-LM/megatron/training.py", line 360, in train_step
    varuna_step_func(data_iterator, model)
  File "/home/ubuntu/varuna_examples/Megatron-LM/pretrain_gpt2.py", line 117, in varuna_step
    loss, overflow, global_norm = model.step(inputs)
  File "/home/ubuntu/varuna/varuna/varuna.py", line 280, in step
    self.average_loss, fwd_time = self.pipeline.run()
  File "/home/ubuntu/varuna/varuna/pipeline.py", line 312, in run
    torch.distributed.barrier(group=self.pipeline_group)
  File "/opt/conda/envs/varuna/lib/python3.9/site-packages/torch/distributed/distributed_c10d.py", line 2783, in barrier
    work.wait()
RuntimeError: [/opt/conda/conda-bld/pytorch_1646755888534/work/third_party/gloo/gloo/transport/tcp/pair.cc:589] Read error [172.31.21.137]:55521: Connection reset by peer
